server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: RatingService    
 
  application:
    name: RatingService
    
eureka:
  instance:
    prefer-ip-address: true
    
okta:
  oauth2:
    issuer: https://dev-59401106.okta.com/oauth2/default
    audience: api://default
    
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
  